services:
  - type: web
    name: testfastapi-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: STEAM_API_KEY
        sync: false  # Tu l’ajouteras manuellement dans Render
